# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: "true"
  branches:
    include:
    - master

variables:
  imageName: 'your-container-image-name:$(build.buildId)'

stages:
- stage: "Default"
  jobs:
  - job: "InstallNetCore"
    steps:
    - task: DotNetCoreInstaller@0
      inputs:
        version: "2.2.x"
  - job: "NugetRestore"
    steps:
    - script: dotnet restore
  - job: "Build"
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration Release'
  - job: "RunTests"
