steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: "2.2.203"
- script: dotnet restore
- script: dotnet build
# - task: DotNetCoreCLI@2
#   displayName: Build
#   inputs:
#     command: build
#     projects: '**/*.csproj'
#     arguments: '--configuration Release'

trigger:
  batch: "true"
  branches:
    include:
    - development