stages:
- stage: "Prerequisites"
  jobs:
  - job:
    steps:
    - task: DotNetCoreInstaller@0
      inputs:
        version: "2.2.203"
- stage: "Dependencies"
  jobs:
  - job:
    steps:
    - script: dotnet restore
- stage: "Build"
  jobs:
  - job:
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration Release'
- stage: "Tests"
  jobs:
  - job: "RunTests"

trigger:
  batch: "true"
  branches:
    include:
    - development